### PR TITLE
Remove limit maximum number of files

### LINKED ISSUE #10: 2^16 file limit it too small for a RocksDB directory
```
$ find data/ -type f | wc -l
90103
```

```
$ fastsync send 141.94.242.56:12345 data/
thread 'main' panicked at src/main.rs:113:9:                       
Can transfer at most 2^16 files.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

### PR DESCRIPTION
**Pull request by DavidVentura**
Fixes #10.

After the naive implementation (just bumping the u16 and protocol version), `fastsync` crashed with "too many open files" -- this is why I changed the fds to be opened on demand (leading to vanishing file precautions)

The test with 20k files runs in 0.8s on my machine.

### CODE REVIEW

**Review by kucharskim — DISMISSED** [review]
Not ready yet.

File: src/main.rs [hunk 1]
```diff
@@ -457,28 +471,29 @@ impl FileReceiver {
...
+
+            // Resize the file to its final size already:
+            // * So that the file system can do a better job of allocating
+            //   a single extent for it, and it doesn't have to fragment
+            //   the file.
+            // * If we run out of space, we learn about that before we waste
+            //   time on the transfer (although then maybe we should do it
+            //   before we receive a chunk after all?).
+            // This can make debugging a bit harder, because when you look
+            // at just the file size you might think it's fully transferred.
```
Comment (kucharskim) [inline src/main.rs:489]: Hm.. this is not resume friendly. If transfer fails in the middle, based on size we wouldn't know transfer was not done. I am not sure is this worth it.

Comment (kucharskim) [reply src/main.rs:489]: I guess it would be fine, if target is temporary location, which will be renamed into place after the transfer. That would be better.

File: src/main.rs [hunk 2]
```diff
@@ -427,12 +443,10 @@ struct Chunk {
 struct FileReceiver {
     fname: String,
 
-    /// The file we’re writing to, if we have started writing.
-    ///
     /// We don’t open the file immediately so we don’t create a zero-sized file
     /// when a transfer fails. We only open the file after we have at least some
     /// data for it.
-    out_file: Option<File>,
+    file_created: bool,
```
Comment (ruuda) [inline src/main.rs:449]: Why does this need to change? It was already acting like a bool (`Some` vs. `None`) and it was already preventing to re-open the file on every chunk receive. If you want to close the file after the receive is complete to limit the number of open file descriptors, we can change it to something with three states (like for sending), something like

```rust
enum FileReceiveState {
    /// We have received zero chunks so far.
    Pending,
    InProgress {
        file: File,
        pending: HashMap<u64, Chunk>,
        offset: u64,
    },
    Done,
}
```

**Review by ruuda — COMMENTED** [review]
I have some suggestions. I admit that I am totally over-engineering this, but on the other hand, this _is_ kind of the toy project where we get to do that and it’s not a lot of work, so let’s make it faster :smiling_imp:

File: src/main.rs [hunk 3]
```diff
@@ -113,11 +113,11 @@ impl TransferPlan {
 
 /// The index of a file in the transfer plan.
 #[derive(BorshDeserialize, BorshSerialize, Copy, Clone, Debug, Eq, Hash, PartialEq)]
-struct FileId(u16);
+struct FileId(u64);
```
[the remark this answers is not in the document]
Comment (DavidVentura) [reply src/main.rs:116]: I was in the same state - but if ext4 thinks 2^32 is a reasonable maximum for inodes, maybe we should too.

[the remark this answers is not in the document]
Comment (ruuda) [reply src/main.rs:116]: palpatine-optimization

File: src/main.rs [hunk 4]
```diff
@@ -250,10 +287,19 @@ impl SendState {
             borsh::to_vec(&header)?.len()
         );
 
+        let in_fd = if let SendStateInner::InProgress {
```
Comment (DavidVentura) [inline src/main.rs:290]: ugh, I don't like this. We know that state is guaranteed to be `InProgress` at this point. Is there a nicer way to do this?

File: src/main.rs [hunk 5]
```diff
@@ -717,4 +734,41 @@ mod tests {
             ["0", "a/1", "a/b/2"].map(|f| base_path.join(f).to_str().unwrap().to_owned())
         );
     }
+
+    #[test]
+    fn test_sends_20_thousand_files() {
+        let (events_tx, events_rx) = std::sync::mpsc::channel::<SenderEvent>();
+        let cwd = env::current_dir().unwrap();
+        thread::spawn(|| {
+            let td = TempDir::new_in(".").unwrap();
```
[the remark this answers is not in the document]
Comment (DavidVentura) [reply src/main.rs:775]: It's now done in this weird fashion because we don't allow sending absolute paths

File: src/main.rs (hunk 4 above)
Comment (ruuda) [reply src/main.rs:290]: Since you already do the match above, in addition to returning `offset` from it, we could return `file.as_raw_fd()` from it.

File: src/main.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (ruuda) [reply src/main.rs:767]: Ah, right, yes. But we could chdir into a directory in `/tmp` and run from there? (Or does that break the Rust test runner which by default runs tests in parallel?) (Sorry for being so paranoid, but I seem to be very good at corrupting btrfs file systems even when I’m not actively trying, and my root is on btrfs, I’m not very eager to tempt fate like this :speak_no_evil:)

File: src/main.rs [hunk 6]
```diff
@@ -229,10 +234,44 @@ impl ChunkHeader {
...
+        let mut state = self.state.lock();
+        let (offset, in_fd) = match *state {
+            SendStateInner::Pending { ref fname } => {
+                let res = std::fs::File::open(fname);
+                if let Err(ref e) = res {
+                    if e.kind() == std::io::ErrorKind::NotFound {
+                        return Ok(SendResult::FileVanished);
+                    }
+                }
+                let res = res?;
```
Comment (ruuda) [inline src/main.rs:251]: 0/5 maybe slightly nicer, but a matter of preference:
```suggestion
                let res = match std::fs::File::open(fname) {
                    Ok(f) => f,
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(SendResult::FileVanished);
                    Err(e) => return Err(e),
                };
```

File: src/main.rs [hunk 7]
```diff
@@ -229,10 +234,44 @@ impl ChunkHeader {
...
+                (offset, file.as_raw_fd())
+            }
+        };
+
         let end = self.len.min(offset + MAX_CHUNK_LEN);
 
         if offset >= self.len || offset >= end {
+            *state = SendStateInner::Done;
             return Ok(SendResult::Done);
         }
```
Comment (ruuda) [inline src/main.rs:276]:
```suggestion
        }
        mem::drop(state);
```

The lock guard by default will live until the end of the scope, which means only one thread will be able to send chunks from this file, it holds the lock even across the `sendfile` syscall. If we drop the lock guard here after we are done with the bookkeeping, then multiple threads can send from the same file in parallel.

File: src/main.rs [hunk 8]
```diff
@@ -488,7 +527,6 @@ impl FileReceiver {
             self.offset += chunk.data.len() as u64;
         }
 
-        self.out_file = Some(out_file);
```
Comment (ruuda) [inline src/main.rs:491]: We should preserve this one! Without it, we’re still re-opening the file for every chunk received!

**Review by ruuda — COMMENTED** [review]
Looks almost good, but I caught a few more issues.

**Review by ruuda — APPROVED** [review]
LGTM :shipit:
